// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptrefrmsnzgkxvmnjyjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0cmVmcm1zbnpna3h2bW5qeWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTMzMTgsImV4cCI6MjA3MjQ4OTMxOH0.ghnuC9MUtfCK-I-3LKqQiyRMaaBkX34g6tX2AJPQo74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});